export const matches2 = [
  {
    homeTeam: 'team a',
    homeTeamGoals: 1,
    homeTeamFPP: 0,
    awayTeam: 'team b',
    awayTeamGoals: 1,
    awayTeamFPP: 0,
  },
  {
    homeTeam: 'team c',
    homeTeamGoals: 2,
    homeTeamFPP: 0,
    awayTeam: 'team d',
    awayTeamGoals: 2,
    awayTeamFPP: 0,
  },
  {
    homeTeam: 'team a',
    homeTeamGoals: 1,
    homeTeamFPP: 0,
    awayTeam: 'team c',
    awayTeamGoals: 1,
    awayTeamFPP: 0,
  },
  {
    homeTeam: 'team b',
    homeTeamGoals: 1,
    homeTeamFPP: 0,
    awayTeam: 'team d',
    awayTeamGoals: 1,
    awayTeamFPP: 0,
  },
  {
    homeTeam: 'team a',
    homeTeamGoals: 1,
    homeTeamFPP: 0,
    awayTeam: 'team d',
    awayTeamGoals: 1,
    awayTeamFPP: 0,
  },
  {
    homeTeam: 'team b',
    homeTeamGoals: 2,
    homeTeamFPP: 0,
    awayTeam: 'team c',
    awayTeamGoals: 2,
    awayTeamFPP: 0,
  },
]

export const matches = [
  {
    homeTeam: 'team a',
    homeTeamGoals: 1,
    homeTeamFPP: -7,
    awayTeam: 'team b',
    awayTeamGoals: 4,
    awayTeamFPP: 0,
  },
  {
    homeTeam: 'team c',
    homeTeamGoals: 1,
    homeTeamFPP: -6,
    awayTeam: 'team d',
    awayTeamGoals: 1,
    awayTeamFPP: 0,
  },
  {
    homeTeam: 'team a',
    homeTeamGoals: 3,
    homeTeamFPP: 0,
    awayTeam: 'team c',
    awayTeamGoals: 0,
    awayTeamFPP: 0,
  },
  {
    homeTeam: 'team b',
    homeTeamGoals: 0,
    homeTeamFPP: -8,
    awayTeam: 'team d',
    awayTeamGoals: 0,
    awayTeamFPP: 0,
  },
  {
    homeTeam: 'team a',
    homeTeamGoals: 0,
    homeTeamFPP: 0,
    awayTeam: 'team d',
    awayTeamGoals: 0,
    awayTeamFPP: 0,
  },
  {
    homeTeam: 'team b',
    homeTeamGoals: 0,
    homeTeamFPP: 0,
    awayTeam: 'team c',
    awayTeamGoals: 3,
    awayTeamFPP: 0,
  },
]
